// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPNG(arg1, arg2) {
  return window['go']['main']['App']['ExportPNG'](arg1, arg2);
}

export function ExportSVG(arg1, arg2) {
  return window['go']['main']['App']['ExportSVG'](arg1, arg2);
}

export function GetDefaultProject() {
  return window['go']['main']['App']['GetDefaultProject']();
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveProject(arg1, arg2) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2);
}
